# Generated by Django 4.2.7 on 2024-02-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="files_loaded")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("owner", models.CharField(blank=True, max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "LOADED"), (1, "IN WORK"), (2, "CONVERTED"), (3, "ERROR")], default=0
                    ),
                ),
                ("info", models.CharField(blank=True, max_length=300)),
                ("result_file", models.FileField(blank=True, upload_to="pdf_convert")),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_ttl", models.IntegerField(default=20160, verbose_name="file live time (min)")),
                ("auto_remove", models.BooleanField(default=False, verbose_name="auto remove old converter")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
