version: '3.7'

services:
  web:
    build:
      context: ./src/web
      dockerfile: ./docker/Dockerfile_django
    command: python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env
    volumes:
      #- ./src/web:/usr/src/app/
      - media_files:/usr/src/app/media/
      - db:/usr/src/app/db/
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    build:
      context: ./src/web
      dockerfile: ./docker/Dockerfile_worker
    command: celery -A core worker --loglevel=info
    env_file:
      - .env

    volumes:
      - media_files:/usr/src/app/media/
      - db:/usr/src/app/db/

    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: ./src/web
      dockerfile: ./docker/Dockerfile_django
    command: celery -A core beat --loglevel=info
    env_file:
      - .env

    depends_on:
      - web
      - redis



  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  dashboard:
    build:
      context: ./src/web
      dockerfile: ./docker/Dockerfile_django
    command: celery -A core flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555

    env_file:
      - .env

    depends_on:
      - web
      - redis
      - celery

volumes:
  media_files:
  db:

